project_id_env: CROWDIN_VERDACCIO_PROJECT_ID
api_token_env: CROWDIN_VERDACCIO_API_KEY

preserve_hierarchy: true

files:
  [
    {
      source: 'packages/plugins/ui-theme/src/i18n/crowdin/**/*',
      translation: '/packages/plugins/ui-theme/src/i18n/download_translations/%locale%/**/%original_file_name%',
    },
  ]
