name: Changesets

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - master

env:
  CI: true

jobs:
  # Update package versions from changesets.
  version:
    timeout-minutes: 14
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install pnpm
        run: npm i pnpm@latest -g
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMJS_PUBLISH_TOKEN }}" > .npmrc
      - name: install dependencies
        run: pnpm install
      - name: crowdin download
        env:
          CROWDIN_VERDACCIO_PROJECT_ID: ${{ secrets.CROWDIN_VERDACCIO_PROJECT_ID }}
          CROWDIN_VERDACCIO_API_KEY: ${{ secrets.CROWDIN_VERDACCIO_API_KEY }}
          CONTEXT: production
        run: pnpm crowdin:download
      - name: build
        run: pnpm build
      - name: create versions
        uses: changesets/action@master
        with:
          version: pnpm ci:version
          commit: 'build: release packages'
          title: 'build: release packages'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
