name: Visual Snapshots

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Run Percy to check visual changes
        uses: percy/exec-action@v0.3.1
        with:
          command: "yarn test:e2e"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}